author = "ajeetdsouza"
description = "A smarter cd command. Supports all major shells."
homepage = "https://github.com/ajeetdsouza/zoxide"
license = "MIT"
binaries = [
    "bin/zoxide"
]
name = "zoxide"
deps = []
chmod = []
