author = "CarterLi"
description = "Like neofetch, but much faster because written mostly in C."
homepage = "https://github.com/fastfetch-cli/fastfetch"
license = "MIT"
binaries = [
    "bin/fastfetch",
    "bin/flashfetch"
]
name = "fastfetch"
deps = []
chmod = []
