author = "X-L-R-G-B"
description = "School project programming language"
homepage = "https://github.com/X-R-G-B/Leviator"
license = "MIT"
binaries = [
    "bin/lvtc",
    "bin/lvtrun"
]
name = "leviator"
deps = []
chmod = []
