author = "BurntSushi"
description = "ripgrep recursively searches directories for a regex pattern while respecting your gitignore"
homepage = "https://github.com/BurntSushi/ripgrep"
license = "MIT"
binaries = [
    "bin/rg",
]
name = "ripgrep"
deps = []
chmod = []
