author = "wez"
description = "A GPU-accelerated cross-platform terminal emulator and multiplexer written by @wez and implemented in Rust"
homepage = "https://wezfurlong.org/wezterm/"
license = "MIT"
binaries = [
    "usr/bin/wezterm",
    "usr/bin/wezterm-gui",
    "usr/bin/wezterm-mux-server",
    "usr/bin/strip-ansi-escapes"
]
name = "wezterm"
deps = []
