author = "wez"
description = "A GPU-accelerated cross-platform terminal emulator and multiplexer written by @wez and implemented in Rust"
homepage = "https://wezfurlong.org/wezterm/"
license = "MIT"
binaries = [
    "wezterm",
]
name = "wezterm"
deps = []
