name: Generate Packages

on:
  release:
    types: [published]

jobs:
  generate:
    name: Generate Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Packages
        run: .github/workflows/generate_packages.sh

      - name: Upload zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in /tmp/packages/*.zip; do
            echo "Uploading $file on tag ${{ github.event.release.tag_name }}"
            echo "else: ${{ github.event.release.id }}"
            gh release upload ${{ github.event.release.tag_name }} "$file"
          done
