name: Generate Packages

on:
  release:
    types: [published]

jobs:
  generate:
    permissions: write-all
    name: Generate Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Packages
        run: .github/workflows/generate_packages.sh

      - name: Upload zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in /tmp/packages/*.zip; do
            gh release upload "${{ github.event.release.tag_name }}" "$file"
          done

      - name: Add failed package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -f /tmp/packages-failed.log ]]; then
            gh release view --json body --jq '.body' > notes.txt
            echo "---" >> notes.txt
            cat /tmp/packages-failed.log >> notes.txt
            gh release edit "${{ github.event.release.tag_name }}" --notes-file notes.txt
          fi
