name: Generate Packages

on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  starting-job:
    permissions: write-all
    name: Add Cron Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add Cron Message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=$(gh release view --json name --jq '.name')
          gh release view --json body --jq '.body' > notes.txt
          echo "---" >> notes.txt
          echo "## Starting Job $(date '+%Y-%m-%d %H:%M')" >> notes.txt
          echo "" >> notes.txt
          gh release edit "$tag_name" --notes-file notes.txt

  generate-package-paq:
    permissions: write-all
    name: Generate Packages Paq
    runs-on: ubuntu-latest
    outputs:
      failed: ${{ steps.failed.outputs.failed }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate Package
        run: .github/workflows/generate_package.sh "./packages/paq"

      - name: create failed
        id: failed
        run: |
          if [[ -f /tmp/packages-failed.log ]]; then
            echo "failed=\"$(cat /tmp/packages-failed.log)\"" >> $GITHUB_OUTPUT
          else
            echo "failed=\"\"" >> $GITHUB_OUTPUT
          fi

      - name: Upload zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=$(gh release view --json name --jq '.name')
          for file in /tmp/packages/*.zip; do
            gh release upload "$tag_name" "$file" --clobber
          done

  generate-package-alacritty:
    permissions: write-all
    name: Generate Packages Alacritty
    runs-on: ubuntu-latest
    outputs:
      failed: ${{ steps.failed.outputs.failed }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u '+%Y%m%d%H%M')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Generate Package
        run: .github/workflows/generate_package.sh "./packages/alacritty"

      - name: create failed
        id: failed
        run: |
          if [[ -f /tmp/packages-failed.log ]]; then
            echo "failed=\"$(cat /tmp/packages-failed.log)\"" >> $GITHUB_OUTPUT
          else
            echo "failed=\"\"" >> $GITHUB_OUTPUT
          fi

      - name: Upload zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=$(gh release view --json name --jq '.name')
          for file in /tmp/packages/*.zip; do
            gh release upload "$tag_name" "$file" --clobber
          done

  generate-packages-1:
    permissions: write-all
    name: Generate Packages 1
    outputs:
      failed: ${{ steps.failed.outputs.failed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Package
        run: .github/workflows/generate_packages.sh "./packages/paq" "./packages/alacritty"

      - name: create failed
        id: failed
        run: |
          if [[ -f /tmp/packages-failed.log ]]; then
            echo "failed=\"$(cat /tmp/packages-failed.log)\"" >> $GITHUB_OUTPUT
          else
            echo "failed=" >> $GITHUB_OUTPUT
          fi

      - name: Upload zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=$(gh release view --json name --jq '.name')
          for file in /tmp/packages/*.zip; do
            gh release upload "$tag_name" "$file" --clobber
          done

  generate-failed:
    permissions: write-all
    name: Generate Failed
    runs-on: ubuntu-latest
    needs: [generate-package-paq, generate-packages-1, generate-package-alacritty]
    steps:
      - uses: actions/checkout@v4

      - name: Add failed package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=$(gh release view --json name --jq '.name')
          cat > /tmp/packages-failed.log <<EOF
            ${{ needs.generates-package-1.outputs.failed }}
            ${{ needs.generate-package-paq.outputs.failed }}
          EOF
          if [[ -f /tmp/packages-failed.log ]] && [[ -n $(cat /tmp/packages-failed.log) ]]; then
            gh release view --json body --jq '.body' > notes.txt
            echo "---" >> notes.txt
            cat /tmp/packages-failed.log >> notes.txt
            gh release edit "$tag_name" --notes-file notes.txt
          fi

  generate-metas:
    permissions: write-all
    name: Generate Metas
    runs-on: ubuntu-latest
    needs: [generate-package-paq, generate-packages-1, generate-package-alacritty]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r ./.github/workflows/requirements_generate_metadata.txt

      - name: Generate Metas
        run: python .github/workflows/generate_metadata.py

      - name: Upload meta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=$(gh release view --json name --jq '.name')
          gh release upload "$tag_name" "/tmp/paq-packages.toml" --clobber

  ending-job:
    permissions: write-all
    name: Add Cron Message
    runs-on: ubuntu-latest
    needs: [generate-metas, generate-failed]
    steps:
      - uses: actions/checkout@v4

      - name: Add Cron Message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=$(gh release view --json name --jq '.name')
          gh release view --json body --jq '.body' > notes.txt
          echo "" >> notes.txt
          echo "## Ending Job $(date '+%Y-%m-%d %H:%M')" >> notes.txt
          echo "" >> notes.txt
          gh release edit "$tag_name" --notes-file notes.txt
